"""Add register_at column and update phone_num column to accept 14 chars

Revision ID: c8eae743c318
Revises: 1e7a01fdacbd
Create Date: 2021-11-08 11:16:32.671987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8eae743c318'
down_revision = '1e7a01fdacbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('register_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'register_at')
    # ### end Alembic commands ###
